# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-19 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190319_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='post',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='gallery/'),
            preserve_default=False,
        ),
    ]
