# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20190320_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Category'),
        ),
    ]
